### PR TITLE
added an overpass time estimator

### PR DESCRIPTION
**Pull request by bjorn-stevens**
I thought this would be something you could also use in the HAMP repo .. hence pinging you to review.

### CODE REVIEW

**Review by JakobDeutloff — APPROVED** [review]
Looks good to me. One could give more specific variable names like ec_track and bahamas and add a parameters section in the docstring that describes the required input (level0 bahamas dataset and ec_track). But fine for me to merge it as it is.

**Comment by yoctoyotta1024** [comment]
I agree with Jakob - better naming would be useful but it's helpful nonetheless :)
Thanks!

**Comment by yoctoyotta1024** [comment]
We're using this calculation in our repository too now :) (see https://github.com/JakobDeutloff/hamp_processing/pull/31)

I could've wrapped our function around yours (probably would've been better coding practice) but in this case it's so small I thought it was easier and a bit clearer just to do old-fashioned copy and paste (plus a bit of editing...)

Thanks for the idea!

**Comment by lkluft** [comment]
> We're using this calculation in our repository too now :) (see [JakobDeutloff/hamp_processing#31](https://github.com/JakobDeutloff/hamp_processing/pull/31))
> 
> I could've wrapped our function around yours (probably would've been better coding practice) but in this case it's so small I thought it was easier and a bit clearer just to do old-fashioned copy and paste (plus a bit of editing...)
> 
> Thanks for the idea!


Looking forward to when one or the other function gets updated and they slowly start to diverge, adding their part to the inevitable increase of entropy in the universe ☺️

**Pull request merged**
