### PR TITLE
added overpass_time estimator

### PR DESCRIPTION
**Pull request by bjorn-stevens**
This was the overpass estimator using the great circle functions that we thought might be of more general interest.  Could replace what is used in the HAMP repo.

### CODE REVIEW

**Comment by bjorn-stevens** [comment]
This worked well for me.. I might need some help meeting the integration tests.

**Comment by lkluft** [comment]
It seems like your PR is removing some functions (and fixes) that were introduced in previous merges. My guess is that this is causing the tests to fail

**Comment by bjorn-stevens** [comment]
I thought I pulled everything... I'll start again and see if it gets better.

**Comment by d70-t** [comment]
It looks a bit like you pulled everything and then blindly overwrote the file with an old copy, instead of integrating your changes. Hope this helps debugging.

**Comment by d70-t** [comment]
A `git reset HEAD^` and then `git add -p` to add only those pieces you really want to commit should help.
Finally, you'll have to do a new `git commit` and a `git push --force-with-lease`.

**Pull request closed without merging**
